// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAINoZhkim1F81iAPJl_7VkfV2flugTv74',
    appId: '1:727183957684:web:f0c7c035b3a992cef981e1',
    messagingSenderId: '727183957684',
    projectId: 'master-flutter-g11',
    authDomain: 'master-flutter-g11.firebaseapp.com',
    storageBucket: 'master-flutter-g11.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDXfHxjDl7Ot8Z6NHaO9DgPJ_yo5XsJoU',
    appId: '1:727183957684:android:fad817faf045037cf981e1',
    messagingSenderId: '727183957684',
    projectId: 'master-flutter-g11',
    storageBucket: 'master-flutter-g11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-MKbe5HYyrFgGDV1KNZA86yb8P64Wgls',
    appId: '1:727183957684:ios:9179957a48ac0e19f981e1',
    messagingSenderId: '727183957684',
    projectId: 'master-flutter-g11',
    storageBucket: 'master-flutter-g11.appspot.com',
    iosBundleId: 'com.example.ceitMasterG11',
  );
}
